GiantBooks\Bundle\ApiBundle\Entity\ActionLog:
    type: entity
    table: action_log
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        action:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        descr:
            type: string
            nullable: false
            length: 4000
            fixed: false
            comment: ''
        createDate:
            type: date
            nullable: false
            comment: ''
            column: create_date
        clientIp:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: client_ip
        serverId:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: server_id
    lifecycleCallbacks: {  }
