GiantBooks\Bundle\ApiBundle\Entity\Book:
    type: entity
    table: book
    indexes:
        IDX_BOOK_TO_CATEGORY:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        descr:
            type: string
            nullable: false
            length: 4000
            fixed: false
            comment: ''
        createDate:
            type: date
            nullable: false
            comment: ''
            column: create_date
        writenFromDate:
            type: date
            nullable: false
            comment: ''
            column: writen_from_date
        writenToDate:
            type: date
            nullable: false
            comment: ''
            column: writen_to_date
        lastUpdate:
            type: date
            nullable: false
            comment: ''
            column: last_update
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
