GiantBooks\Bundle\ApiBundle\Entity\Category:
    type: entity
    table: category
    indexes:
        IDX_CATEGORY_TO_ITSELF:
            columns:
                - parent_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        lastUpdate:
            type: date
            nullable: false
            comment: ''
            column: last_update
    manyToOne:
        parent:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
