GiantBooks\Bundle\ApiBundle\Entity\City:
    type: entity
    table: city
    indexes:
        IDX_CITY_TO_COUNTRY:
            columns:
                - country_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        city:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        lastUpdate:
            type: date
            nullable: true
            comment: ''
            column: last_update
    manyToOne:
        country:
            targetEntity: Country
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
