GiantBooks\Bundle\ApiBundle\Entity\Person:
    type: entity
    table: person
    indexes:
        IDX_PERSON_TO_ADDR:
            columns:
                - addr_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        lname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        birth:
            type: date
            nullable: true
            comment: ''
        gender:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        createDate:
            type: date
            nullable: true
            comment: ''
            column: create_date
        lastUpdate:
            type: date
            nullable: true
            comment: ''
            column: last_update
    manyToOne:
        addr:
            targetEntity: Addr
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                addr_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
