GiantBooks\Bundle\ApiBundle\Entity\UploadBookData:
    type: entity
    table: upload_book_data
    indexes:
        IDX_UPLOADBOOKDATA_TO_MEMBER:
            columns:
                - member_id
        IDX_UPLOADBOOKDATA_TO_BOOK:
            columns:
                - book_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        pages:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        partNumber:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: part_number
        uploadDate:
            type: date
            nullable: false
            comment: ''
            column: upload_date
    manyToOne:
        book:
            targetEntity: Book
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                book_id:
                    referencedColumnName: id
            orphanRemoval: false
        member:
            targetEntity: Member
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
